title: Shayan Jalali
logo: docs/assets/#ffcc00_20250524_020001_0000.png
description: Personal academic and research website of Shayan Jalaeian — a master's student in Medical Biotechnology with a focus on bioinformatics, data analysis, and computational biology. This site features my projects, publications, skills, and CV.
theme: jekyll-theme-minimal
